project_id = "grlgdzknfgpkzcyemgys"

[functions.create-couple-space]
verify_jwt = false

[functions.join-couple-space]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.generate-vapid-keys]
verify_jwt = false