import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const FALLBACK: Record<string, { title: string; description: string }[]> = {
  romantico: [
    { title: "Jantar à luz de velas em casa", description: "Cozinhem juntos e criem uma noite especial sem sair de casa." },
    { title: "Carta de amor surpresa", description: "Escreve uma carta sincera e deixa-a num sítio inesperado." },
    { title: "Pôr do sol juntos", description: "Parem tudo e assistam ao pôr do sol num lugar bonito." },
    { title: "Noite sem telemóveis", description: "Uma noite inteira só para vocês dois, sem ecrãs." },
    { title: "Dança na sala", description: "Ponham uma música especial e dancem juntos em casa." },
    { title: "Recrear o primeiro encontro", description: "Voltem ao mesmo lugar e repitam o que fizeram na primeira vez." },
    { title: "Surpresa de manhã", description: "Prepara o pequeno-almoço favorito do teu par sem avisar." },
    { title: "Noite de estrelas", description: "Deitem-se ao ar livre e observem o céu estrelado juntos." },
    { title: "Mensagens escondidas pela casa", description: "Deixa post-its com palavras carinhosas em sítios que o teu par vai encontrar." },
    { title: "Banho relaxante a dois", description: "Prepara um banho com velas, sais e música para os dois." },
    { title: "Álbum de memórias em conjunto", description: "Passem uma tarde a montar um álbum com as vossas fotos favoritas." },
    { title: "Poema escrito à mão", description: "Escreve um poema — mesmo simples — dedicado ao teu par." },
    { title: "Surpresa no trabalho", description: "Envia flores ou uma mensagem especial ao teu par no trabalho." },
    { title: "Sessão de fotos juntos", description: "Saiam para tirar fotos bonitas dos dois no vosso sítio favorito." },
    { title: "Playlist do casal", description: "Criem juntos uma playlist com as músicas que marcaram a vossa relação." },
    { title: "Noite de spa em casa", description: "Façam máscaras, massagens e cuidem um do outro em casa." },
    { title: "Ler poesia em voz alta", description: "Cada um escolhe um poema e lê ao outro à luz de uma vela." },
    { title: "Mini escapadela surpresa", description: "Planeia uma saída de um dia para um lugar que o teu par adore." },
    { title: "Jogo das memórias a dois", description: "Escrevam 20 memórias juntos e leiam-nas em voz alta a rir." },
    { title: "Cozinhar a receita favorita", description: "Peçam a receita favorita um do outro e cozinhem-na juntos." },
    { title: "Mensagem de voz especial", description: "Grava uma mensagem de voz a dizer o que sentes e envia de surpresa." },
    { title: "Desenhar o retrato um do outro", description: "Tentem desenhar-se mutuamente — o resultado vai fazer rir." },
    { title: "Assistir ao nascer do sol", description: "Acordem cedo e vejam o nascer do sol juntos com café quente." },
    { title: "Noite de cartas e jogos", description: "Joguem um jogo de cartas e o vencedor escolhe a próxima atividade." },
    { title: "Criar um ritual diário", description: "Inventem um gesto pequeno que vão repetir todos os dias — um abraço longo, um beijo especial." },
    { title: "Visitar um mercado local", description: "Passem a manhã num mercado e cozinhem com o que comprarem." },
    { title: "Noite de cinema em casa", description: "Montem uma área confortável com pipocas e assistam ao favorito de cada um." },
    { title: "Escrever votos renovados", description: "Escrevam votos informais um para o outro e leiam-nos num jantar especial." },
    { title: "Recrear uma foto antiga", description: "Escolham uma foto de quando se conheceram e recriem-na agora." },
    { title: "Passear de mãos dadas sem destino", description: "Saiam sem plano e deixem-se guiar pelo momento." },
    { title: "Surpresa de comida favorita", description: "Compra ou cozinha a comida favorita do teu par sem ele saber." },
    { title: "Escrever o que amam um no outro", description: "Cada um escreve 10 coisas que ama no outro e trocam as listas." },
    { title: "Noite de jogos românticos", description: "Joguem um jogo que inclua perguntas íntimas e desafios a dois." },
    { title: "Visitar o lugar onde se conheceram", description: "Voltem ao sítio onde tudo começou e revivam esse momento." },
    { title: "Fazer uma lista de sonhos juntos", description: "Escrevam uma lista de 50 coisas que querem fazer juntos na vida." },
    { title: "Noite de fondue", description: "Preparem um fondue de chocolate ou queijo e aproveitem a intimidade." },
    { title: "Tarde de desenho juntos", description: "Comprem materiais e passem uma tarde a desenhar o que quiserem." },
    { title: "Surpresa com bilhetes para algo", description: "Compra bilhetes para um concerto, peça ou evento que o teu par adore." },
    { title: "Criar um cocktail do casal", description: "Inventem juntos uma bebida especial e deem-lhe um nome." },
    { title: "Noite de karaoke romântico", description: "Cantem músicas de amor um para o outro sem vergonha." },
    { title: "Spa day em casa", description: "Dediquem o dia inteiro a cuidar um do outro — massagem, esfoliação, hidratação." },
    { title: "Assistir a um musical juntos", description: "Escolham um musical clássico e assistam com boa disposição." },
    { title: "Tarde de fotografia artística", description: "Saiam com câmara e fotografem o que vos parece bonito — depois partilhem." },
    { title: "Planear uma viagem dos sonhos", description: "Mesmo sem data, planeem detalhadamente a viagem que sempre quiseram." },
    { title: "Carta para ler daqui a um ano", description: "Cada um escreve uma carta para o outro abrir no próximo aniversário." },
    { title: "Criar uma tradição nova", description: "Inventem um ritual que vão repetir todos os anos juntos." },
    { title: "Noite de gastronomia internacional", description: "Escolham um país e cozinhem um menu completo dessa cultura." },
    { title: "Sessão de leitura a dois", description: "Leiam em voz alta um para o outro durante uma hora." },
    { title: "Montar um puzzle juntos", description: "Escolham um puzzle difícil e completem-no ao longo de vários dias." },
    { title: "Tarde de voluntariado juntos", description: "Passem uma tarde a ajudar uma causa que ambos valorizam." },
  ],
  aventura: [
    { title: "Explorar um bairro novo", description: "Escolham um sítio que nunca visitaram e percorram-no a pé." },
    { title: "Piquenique surpresa", description: "Um de vocês organiza tudo em segredo e surpreende o outro." },
    { title: "Experimentar uma comida nova", description: "Escolham um restaurante de culinária que nunca provaram." },
    { title: "Caminhada na natureza", description: "Encontrem uma trilha e passem o dia ao ar livre juntos." },
    { title: "Road trip de um dia", description: "Escolham uma direção e descubram o que encontram pelo caminho." },
    { title: "Acampar numa noite", description: "Montem tenda e passem uma noite sob as estrelas." },
    { title: "Aula de surf ou paddle", description: "Experimentem um desporto aquático juntos pela primeira vez." },
    { title: "Subir a um miradouro", description: "Encontrem o miradouro mais alto perto de vocês e subam." },
    { title: "Visitar um museu diferente", description: "Escolham um museu temático que nunca visitaram e explorem." },
    { title: "Passeio de bicicleta", description: "Aluguem bicicletas e percorram uma rota nova juntos." },
    { title: "Visitar uma aldeia histórica", description: "Escolham uma aldeia com história e passem o dia a explorá-la." },
    { title: "Aula de escalada indoor", description: "Experimentem escalada num ginásio especializado juntos." },
    { title: "Tarde de geocaching", description: "Usem a app de geocaching e encontrem esconderijos na vossa cidade." },
    { title: "Kayak ou canoa juntos", description: "Aluguem um kayak e explorem um rio ou lago perto de vocês." },
    { title: "Visitar um parque natural", description: "Passem o dia a explorar a fauna e flora de um parque natural." },
    { title: "Festival local", description: "Descubram um festival ou feira na região e participem." },
    { title: "Tarde de paintball", description: "Vivam uma tarde cheia de adrenalina e boa disposição." },
    { title: "Visitar uma feira de antiguidades", description: "Passem a manhã a procurar tesouros escondidos numa feira." },
    { title: "Noite de observação de estrelas", description: "Saiam da cidade e observem o céu com binóculos ou telescópio." },
    { title: "Tour gastronómico", description: "Provem pratos típicos em vários restaurantes da cidade." },
    { title: "Aula de arco e flecha", description: "Experimentem tiro com arco numa escola especializada." },
    { title: "Visitar uma quinta orgânica", description: "Passem o dia a conhecer como os alimentos são produzidos." },
    { title: "Desafio de orientação", description: "Usem apenas um mapa de papel para chegar a um destino novo." },
    { title: "Tarde de tirolesa", description: "Experimentem uma atividade de adrenalina num parque aventura." },
    { title: "Visitar um faro ou castelo", description: "Encontrem uma estrutura histórica perto e explorem-na." },
    { title: "Mergulho ou snorkeling", description: "Explorem o mundo submarino juntos pela primeira vez." },
    { title: "Acampamento de uma tarde", description: "Levem uma manta e comida para um parque e fiquem o dia todo." },
    { title: "Visitar um jardim botânico", description: "Passem a tarde a descobrir plantas e flores exóticas juntos." },
    { title: "Tarde de go-kart", description: "Compitam amigavelmente numa pista de go-kart." },
    { title: "Explorar a cidade à noite", description: "Façam um passeio pela cidade após a meia-noite e descubram-na de outro ângulo." },
    { title: "Visitar um parque de diversões", description: "Passem o dia nas montanhas-russas e nos jogos como crianças." },
    { title: "Tarde de hipismo", description: "Experimentem andar a cavalo juntos numa quinta." },
    { title: "Descobrir praias ou lagos escondidos", description: "Pesquisem e encontrem um lugar de água secreto na região." },
    { title: "Aula de ioga ao ar livre", description: "Encontrem uma sessão de ioga num parque e pratiquem juntos." },
    { title: "Visitar um aquário ou zoo", description: "Passem o dia a descobrir animais e aprender sobre eles." },
    { title: "Tarde de patinagem", description: "Vão a uma pista de patinagem e divirtam-se sem se importar com quedas." },
    { title: "Percurso de montanha", description: "Escolham uma montanha acessível e façam o percurso completo." },
    { title: "Visitar uma vinícola", description: "Façam uma visita guiada a uma vinícola e provem os vinhos." },
    { title: "Tarde de observação de aves", description: "Com binóculos, saiam para identificar o máximo de aves possível." },
    { title: "Explorar mercado de artesanato", description: "Percorram um mercado de artesãos e comprem algo feito à mão." },
    { title: "Visitar uma ilha próxima", description: "Se possível, apanhem um barco e passem o dia numa ilha." },
    { title: "Correr uma corrida juntos", description: "Inscrevam-se numa corrida de 5km e treinem e participem juntos." },
    { title: "Tarde de canoagem", description: "Explorem um rio ou lago de canoa apreciando a natureza." },
    { title: "Visitar uma gruta ou caverna", description: "Encontrem uma gruta acessível e explorem-na juntos." },
    { title: "Tarde de fotografia de rua", description: "Saiam com câmara para fotografar a vida quotidiana da cidade." },
    { title: "Aula de dança de salsa", description: "Inscrevam-se numa aula de salsa ou outro ritmo latino." },
    { title: "Noite de teatro ou ópera", description: "Assistam a um espetáculo cultural que nenhum dos dois já viu." },
    { title: "Visitar uma exposição de arte", description: "Percorram uma galeria e partilhem as vossas interpretações das obras." },
    { title: "Passeio de barco ou vela", description: "Aluguem um barco pequeno e naveguem por algumas horas." },
    { title: "Desafio de escape room", description: "Tentem sair de uma sala de escape antes do tempo acabar." },
  ],
  comunicacao: [
    { title: "36 perguntas do amor", description: "Façam as 36 perguntas científicas que aproximam as pessoas." },
    { title: "Conversa sem julgamentos", description: "Partilhem um medo ou insegurança que nunca disseram em voz alta." },
    { title: "Carta para daqui a 5 anos", description: "Cada um escreve o que espera da relação no futuro." },
    { title: "Agradecer 3 coisas por dia", description: "Durante uma semana, digam 3 coisas que agradecem um ao outro." },
    { title: "Desligar e conversar 1 hora", description: "Uma hora inteira de conversa profunda sem distrações." },
    { title: "Partilhar memória favorita juntos", description: "Cada um conta a sua memória favorita da relação com detalhes." },
    { title: "Dizer o que não conseguem dizer", description: "Escrevam primeiro, depois leiam em voz alta o que é difícil de dizer." },
    { title: "Conversa sobre sonhos", description: "Partilhem os 3 maiores sonhos que ainda não realizaram." },
    { title: "Jogo das perguntas profundas", description: "Escrevam 10 perguntas cada um e respondam honestamente." },
    { title: "Semana de afirmações diárias", description: "Cada dia, digam uma coisa específica que admiram no outro." },
    { title: "Desafio sem crítica por 3 dias", description: "Durante 3 dias, substituam críticas por pedidos construtivos." },
    { title: "Conversa sobre infância", description: "Contem uma história marcante da infância que o outro não conhece." },
    { title: "Partilhar uma preocupação atual", description: "Cada um partilha algo que o está a preocupar — o outro apenas escuta." },
    { title: "Mapear as linguagens do amor", description: "Façam juntos o teste das 5 linguagens do amor e discutam os resultados." },
    { title: "Conversa sobre dinheiro", description: "Discutam abertamente os objetivos financeiros e os valores sobre dinheiro." },
    { title: "Escrever o que mais apreciam", description: "Cada um faz uma lista de 20 coisas que aprecia no outro e trocam." },
    { title: "Contar o dia com detalhes", description: "Durante uma semana, contem o dia com muito detalhe — sem resumos." },
    { title: "Partilhar uma insegurança", description: "Cada um partilha uma insegurança profunda — o outro responde com carinho." },
    { title: "Dizer 'obrigado' por coisas pequenas", description: "Durante 5 dias, agradeçam explicitamente cada pequena ação do outro." },
    { title: "Conversa sobre família", description: "Partilhem como a família de cada um influenciou quem são hoje." },
    { title: "Definir o que é prioridade", description: "Conversem sobre o que é mesmo importante para cada um na vida." },
    { title: "Contar um arrependimento", description: "Cada um partilha algo que faria de forma diferente — sem julgamentos." },
    { title: "Dizer o que precisam mais", description: "Cada um expressa claramente o que mais precisa do outro nesta fase." },
    { title: "Conversa sobre espiritualidade", description: "Partilhem as vossas crenças e visão sobre vida, morte e propósito." },
    { title: "Desafio de escuta ativa", description: "Um fala 10 minutos sem interrupções — o outro só escuta e depois responde." },
    { title: "Partilhar uma conquista pessoal", description: "Cada um conta uma conquista da qual tem muito orgulho e porquê." },
    { title: "Conversa sobre amizades", description: "Partilhem o que valorizam nas amizades e como querem cultivá-las." },
    { title: "Escrever o que mudaria", description: "Com honestidade e amor, partilhem algo que gostariam de mudar na relação." },
    { title: "Conversa sobre saúde mental", description: "Partilhem como se sentem emocionalmente e o que precisam de apoio." },
    { title: "Listar os momentos difíceis superados", description: "Recordem juntos os momentos difíceis que superaram e como os tornaram mais fortes." },
    { title: "Conversa sobre trabalho e ambições", description: "Partilhem onde querem estar profissionalmente daqui a 5 anos." },
    { title: "Dizer o que admiram no outro", description: "Durante 10 minutos, cada um diz o que admira no outro sem parar." },
    { title: "Conversa sobre limites", description: "Discutam o que é importante respeitar um no outro — espaço, tempo, privacidade." },
    { title: "Partilhar algo que nunca disseram", description: "Cada um revela algo sobre si que o outro desconhece completamente." },
    { title: "Conversa sobre envelhecer juntos", description: "Imaginem como querem ser quando forem velhos e o que esperam." },
    { title: "Escrever os medos juntos", description: "Cada um escreve os 3 maiores medos e partilha sem vergonha." },
    { title: "Fazer perguntas como se fosse o primeiro dia", description: "Imaginem que se conheceram hoje e façam perguntas como se fosse a primeira vez." },
    { title: "Desafio da gratidão semanal", description: "Todas as semanas, partilhem 5 coisas pelas quais são gratos — incluindo o outro." },
    { title: "Conversa sobre criação de filhos", description: "Partilhem os valores que querem transmitir aos filhos — ou que já transmitem." },
    { title: "Contar o que os une", description: "Listem tudo o que têm em comum — desde valores a gostos pequenos." },
    { title: "Desafio sem critica 7 dias", description: "Durante uma semana, substituam qualquer crítica por um elogio genuíno." },
    { title: "Partilhar uma fantasia ou sonho louco", description: "Cada um conta um sonho ou fantasia que considera improvável mas adorava viver." },
    { title: "Conversa sobre hobbies e paixões", description: "Cada um explica o hobby favorito como se o outro nunca tivesse ouvido falar." },
    { title: "Dizer o que mudou em vocês", description: "Partilhem como cada um mudou desde que estão juntos — para melhor." },
    { title: "Escrever uma carta de perdão", description: "Escrevam uma carta a perdoar algo — a si próprios ou ao outro." },
    { title: "Conversa sobre herança emocional", description: "Discutam padrões da família de origem que querem manter ou quebrar." },
    { title: "Noite de perguntas aleatórias", description: "Usem um gerador de perguntas e respondam honestamente durante 1 hora." },
    { title: "Partilhar o que os faz sentir amados", description: "Cada um descreve em detalhe o que o faz sentir verdadeiramente amado." },
    { title: "Conversa sobre legado", description: "O que querem que as pessoas digam de vocês quando não estiverem cá?" },
    { title: "Redefinir o relacionamento", description: "Conversem sobre o que querem que a relação seja daqui a 1 ano." },
  ],
  diversao: [
    { title: "Noite de jogos de tabuleiro", description: "Escolham 3 jogos e passem a noite a competir com boa disposição." },
    { title: "Cozinhar um prato novo juntos", description: "Escolham uma receita difícil e tentem fazer juntos." },
    { title: "Maratona de filmes temática", description: "Escolham um tema e vejam filmes o dia todo com snacks." },
    { title: "Desafio de karaoke em casa", description: "Cantem as músicas favoritas um do outro sem vergonha." },
    { title: "Aula de algo novo juntos", description: "Inscrevam-se numa aula — culinária, dança, pintura ou outra." },
    { title: "Torneio de videojogos", description: "Escolham jogos para dois e façam um campeonato de 3 jogos." },
    { title: "Noite de mímica e adivinha", description: "Façam equipas ou joguem os dois a adivinhar palavras por gestos." },
    { title: "Desafio de culinária às cegas", description: "Um cozinha com os olhos vendados e o outro guia apenas com palavras." },
    { title: "Tarde de caricaturas", description: "Tentem desenhar-se mutuamente — sem olhar para o papel." },
    { title: "Jogo do 'Nunca fiz isto'", description: "Joguem ao clássico e conheçam experiências que nunca partilharam." },
    { title: "Desafio de Lego", description: "Comprem um Lego e construam-no juntos em competição amigável." },
    { title: "Noite de trivial ou quiz", description: "Façam um quiz online ou com cartas sobre temas que adoram." },
    { title: "Tarde de origami", description: "Aprendam a fazer origami no YouTube e tentem replicar as figuras." },
    { title: "Desafio de dança TikTok", description: "Aprendam juntos uma coreografia popular e filmem o resultado." },
    { title: "Noite de charadas e enigmas", description: "Encontrem um livro de charadas e tentem resolver o maior número possível." },
    { title: "Construir uma tenda na sala", description: "Usem almofadas e cobertores para criar uma tenda e dormir lá." },
    { title: "Desafio de sushi em casa", description: "Comprem os ingredientes e tentem fazer sushi juntos pela primeira vez." },
    { title: "Tarde de pintura por números", description: "Comprem um kit de pintura por números e completem-no juntos." },
    { title: "Competição de culinária criativa", description: "Cada um tem 30 minutos e os mesmos ingredientes — quem faz o melhor prato?" },
    { title: "Jogo de roleplay de viagem", description: "Imaginem que estão num país diferente e joguem a ser turistas em casa." },
    { title: "Tarde de argila ou cerâmica", description: "Comprem argila e tentem moldar algo — depois troquem as peças." },
    { title: "Noite de improvisação teatral", description: "Criem cenas improvisadas com personagens inventados pelos dois." },
    { title: "Desafio de puzzle gigante", description: "Comprem o maior puzzle que encontrarem e completem-no num fim de semana." },
    { title: "Tarde de costura ou bordado", description: "Aprendam uma técnica básica juntos — cada um faz uma peça para o outro." },
    { title: "Jogo de perguntas engraçadas", description: "Escrevam as perguntas mais absurdas possíveis e respondam sem parar de rir." },
    { title: "Noite de escape room virtual", description: "Joguem um escape room online a dois e tentem resolver antes do tempo." },
    { title: "Tarde de magia e truques", description: "Aprendam um truque de magia no YouTube e tentem enganar amigos." },
    { title: "Desafio de cocktails em casa", description: "Criem 3 cocktails diferentes — o outro tem de adivinhar os ingredientes." },
    { title: "Construção de castelo de cartas", description: "Quem consegue fazer o castelo de cartas mais alto sem cair?" },
    { title: "Noite de stand-up comedy", description: "Cada um prepara 5 minutos de humor e 'atua' para o outro." },
    { title: "Desafio de imitações", description: "Imitem pessoas conhecidas ou personagens e adivinhem quem é." },
    { title: "Tarde de cupcakes decorados", description: "Façam cupcakes e decorem-nos de forma criativa — o mais feio lava a loiça." },
    { title: "Competição de arremesso de papel", description: "Dobrem aviões de papel e vejam quem faz voar mais longe." },
    { title: "Jogo de detetive em casa", description: "Um esconde um 'objeto do crime' e o outro tem 30 minutos para o encontrar." },
    { title: "Tarde de fotografias criativas", description: "Criem fotos temáticas engraçadas em casa com props improvisados." },
    { title: "Noite de batalha de pillow", description: "Regras definidas, travesseiros na mão — o mais tolo vence." },
    { title: "Desafio de comida de olhos fechados", description: "Adivinhem o que estão a comer apenas pelo sabor e textura." },
    { title: "Criar um videoclipe juntos", description: "Escolham uma música e filmem um videoclipe criativo em casa." },
    { title: "Tarde de karts de papel", description: "Construam carros de papel e façam uma corrida improvisada." },
    { title: "Jogo de palavras encadeadas", description: "Joguem ao stop, ao jogo da forca ou inventem um jogo de palavras." },
    { title: "Noite de karaoke de línguas diferentes", description: "Cantem músicas em idiomas que não falam — o mais desafinado ganha." },
    { title: "Desafio do cubo de rubik", description: "Tentem resolver o cubo de rubik — quem fizer em menos tempo?" },
    { title: "Tarde de aquarela", description: "Comprem aquarelas baratas e pintem o mesmo tema — depois comparem." },
    { title: "Construir um LEGO de memória", description: "Olhem para uma imagem 30 segundos e depois construam de memória." },
    { title: "Jogo de perguntas sobre o outro", description: "Quem conhece melhor o par? Testem com perguntas sobre hábitos e preferências." },
    { title: "Desafio de origami competitivo", description: "O mesmo modelo, cronômetro a correr — quem termina primeiro?" },
    { title: "Tarde de música ao vivo", description: "Toquem um instrumento ou cantem juntos sem ensaio prévio." },
    { title: "Fazer doces juntos", description: "Façam brigadeiros, trufas ou bolachas decoradas e partilhem com vizinhos." },
    { title: "Criar um jogo de tabuleiro próprio", description: "Inventem as regras, o tabuleiro e as peças — depois joguem." },
    { title: "Desafio do pino e ginástica", description: "Tentem fazer o pino, a roda e outros movimentos — com segurança." },
    { title: "Noite de sessão de fotos divertidas", description: "Caracterizem-se com roupas e acessórios engraçados e façam um ensaio fotográfico." },
  ],
  crescimento: [
    { title: "Ler o mesmo livro juntos", description: "Escolham um livro e discutam um capítulo por semana." },
    { title: "Definir objetivos do ano", description: "Sentem-se e escrevam juntos os objetivos para os próximos 12 meses." },
    { title: "Meditar juntos 10 minutos", description: "Experimentem uma sessão de meditação guiada em casal." },
    { title: "Voluntariado por um dia", description: "Encontrem uma causa e passem um dia a ajudar juntos." },
    { title: "Podcast ou documentário juntos", description: "Assistam a algo que vos ensine algo novo e debatam no final." },
    { title: "Criar uma visão partilhada", description: "Criem um vision board digital ou físico com os vossos sonhos." },
    { title: "Aprender uma língua nova juntos", description: "Usem o Duolingo ou outra app para aprender 10 palavras por dia numa língua nova." },
    { title: "Jeûm digital de 24 horas", description: "Passem um dia inteiro sem redes sociais e observem como se sentem." },
    { title: "Criar um orçamento familiar", description: "Sentem-se e definam juntos um plano financeiro realista." },
    { title: "Hábito de gratidão diária", description: "Durante 30 dias, escrevam 3 gratidões cada um todas as manhãs." },
    { title: "Desafio de leitura mensal", description: "Cada mês, cada um lê um livro diferente e apresenta ao outro." },
    { title: "Aprender a cozinhar saudável", description: "Façam um curso online de culinária saudável e apliquem durante 2 semanas." },
    { title: "Desafio de 30 dias de exercício", description: "Criem uma rotina de exercício juntos e mantenham-na 30 dias." },
    { title: "Explorar a espiritualidade juntos", description: "Meditem, rezem ou pratiquem mindfulness juntos durante uma semana." },
    { title: "Criar uma poupança conjunta", description: "Definam uma meta e poupem juntos para um objetivo especial." },
    { title: "Aprender a investir", description: "Estudem juntos os conceitos básicos de investimento e dêem o primeiro passo." },
    { title: "Desafio de alimentação consciente", description: "Durante 2 semanas, evitem açúcar processado e avaliem como se sentem." },
    { title: "Criar um projeto conjunto", description: "Iniciem juntos um projeto — um blogue, um negócio ou uma criação artística." },
    { title: "Fazer um curso online juntos", description: "Inscrevam-se num curso que ambos queiram fazer e completem-no." },
    { title: "Desafio de minimalismo", description: "Percorram a casa e doem tudo o que não usam há mais de um ano." },
    { title: "Aprender uma habilidade nova", description: "Escolham uma habilidade — fotografia, culinária, código — e aprendam juntos." },
    { title: "Criar uma rotina matinal juntos", description: "Definam e pratiquem uma rotina matinal saudável durante 2 semanas." },
    { title: "Desafio de sono e descanso", description: "Durante uma semana, durmam 8 horas por noite e observem as mudanças." },
    { title: "Escrever um diário partilhado", description: "Escrevam juntos num diário — cada um escreve uma entrada por dia." },
    { title: "Aprender técnicas de comunicação não violenta", description: "Estudem e apliquem os 4 passos da comunicação não violenta durante uma semana." },
    { title: "Desafio de hidratação", description: "Durante 10 dias, bebam 2 litros de água por dia e registem como se sentem." },
    { title: "Criar um jardim em casa", description: "Plantem ervas aromáticas ou flores e cuidem delas juntos." },
    { title: "Aprender primeiros socorros", description: "Façam um curso de primeiros socorros básicos — é útil para a vida." },
    { title: "Desafio de leitura de notícias construtivas", description: "Durante uma semana, leiam apenas notícias positivas e partilhem uma por dia." },
    { title: "Criar metas trimestrais", description: "Cada trimestre, definam 3 metas pessoais e 3 metas de casal." },
    { title: "Aprender a fazer ioga juntos", description: "Sigam tutoriais de ioga no YouTube durante 2 semanas." },
    { title: "Desafio de telefone fora do quarto", description: "Durante 2 semanas, deixem o telemóvel fora do quarto ao dormir." },
    { title: "Explorar o serviço comunitário", description: "Encontrem uma forma de servir a comunidade regularmente em conjunto." },
    { title: "Ler um livro de autoajuda a dois", description: "Escolham um livro de crescimento pessoal e apliquem os exercícios juntos." },
    { title: "Criar um fundo de emergência", description: "Definam um valor e poupem até atingir 3 meses de despesas guardados." },
    { title: "Aprender sobre saúde integrativa", description: "Estudem juntos nutrição, sono e exercício — e apliquem um princípio novo." },
    { title: "Desafio de criatividade diária", description: "Durante 14 dias, criem algo todos os dias — desenho, texto, música, receita." },
    { title: "Explorar a terapia de casal online", description: "Experimentem uma sessão com um profissional — é investimento, não fraqueza." },
    { title: "Criar um manifesto de casal", description: "Escrevam os vossos valores, missão e visão como casal num documento." },
    { title: "Aprender sobre saúde financeira", description: "Façam juntos um curso gratuito sobre finanças pessoais e apliquem o que aprenderam." },
    { title: "Desafio de tempo na natureza", description: "Durante um mês, passem pelo menos 30 minutos ao ar livre todos os dias." },
    { title: "Criar um clube do livro a dois", description: "Leiam o mesmo livro por mês e discutam-no com perguntas preparadas." },
    { title: "Aprender técnicas de respiração", description: "Aprendam e pratiquem técnicas de respiração para stress durante uma semana." },
    { title: "Desafio de elogios diários", description: "Durante 21 dias, deem um elogio específico e genuíno um ao outro." },
    { title: "Explorar o jejum intermitente juntos", description: "Experimentem jejum intermitente durante 2 semanas e partilhem as experiências." },
    { title: "Criar um plano de saúde anual", description: "Marquem as consultas, exames e check-ups que precisam fazer este ano." },
    { title: "Aprender sobre sustentabilidade", description: "Adotem 3 hábitos sustentáveis em casa durante um mês." },
    { title: "Desafio de aprendizagem contínua", description: "Cada mês, cada um ensina ao outro algo que aprendeu — 30 minutos de aula." },
    { title: "Criar um ritual de revisão semanal", description: "Todas as semanas, revisem o que correu bem, o que melhorar e o que planeiam." },
    { title: "Explorar a psicologia positiva", description: "Leiam sobre psicologia positiva e apliquem 3 exercícios durante 2 semanas." },
    { title: "Fazer um retiro de fim de semana", description: "Passem um fim de semana sem tecnologia, focados em crescer e descansar juntos." },
  ],
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { category } = await req.json();

    const categoryPrompts: Record<string, string> = {
      romantico: "desafios românticos e criativos para casais (encontros, surpresas, cartas de amor, jantares especiais)",
      aventura: "desafios de aventura e exploração para casais (viajar, experimentar coisas novas, atividades ao ar livre)",
      comunicacao: "desafios de comunicação e conexão emocional para casais (conversas profundas, perguntas, vulnerabilidade)",
      diversao: "desafios divertidos e lúdicos para casais (jogos, competições amigáveis, cozinhar juntos)",
      crescimento: "desafios de crescimento pessoal e espiritual para casais (leitura conjunta, oração, meditação, objetivos)"
    };

    const catDesc = categoryPrompts[category] || "desafios variados e criativos para casais";
    const ANTHROPIC_API_KEY = Deno.env.get("ANTHROPIC_API_KEY");

    // Try Anthropic API first
    if (ANTHROPIC_API_KEY) {
      try {
        const response = await fetch("https://api.anthropic.com/v1/messages", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "x-api-key": ANTHROPIC_API_KEY,
            "anthropic-version": "2023-06-01",
          },
          body: JSON.stringify({
            model: "claude-haiku-4-5-20251001",
            max_tokens: 1024,
            system: "És um assistente criativo para casais. Gera desafios únicos, divertidos e significativos para fortalecer a relação. Responde APENAS em JSON válido, sem markdown, sem explicações adicionais.",
            messages: [{
              role: "user",
              content: `Gera exatamente 5 ${catDesc}. Cada desafio deve ter um título curto (máx 50 caracteres) e uma descrição motivadora (máx 120 caracteres). Responde APENAS com um array JSON no formato: [{"title":"...","description":"..."}]`
            }],
          }),
        });

        if (response.ok) {
          const data = await response.json();
          const content = data.content?.[0]?.text || "[]";
          const jsonMatch = content.match(/\[[\s\S]*\]/);
          const challenges = jsonMatch ? JSON.parse(jsonMatch[0]) : [];
          if (challenges.length > 0) {
            return new Response(JSON.stringify({ challenges }), {
              headers: { ...corsHeaders, "Content-Type": "application/json" },
            });
          }
        }
      } catch {
        // fall through to fallback
      }
    }

    // Fallback: pick 5 random challenges from the 50 curated ones
    const pool = FALLBACK[category] || FALLBACK.romantico;
    const shuffled = [...pool].sort(() => Math.random() - 0.5).slice(0, 5);

    return new Response(JSON.stringify({ challenges: shuffled }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  } catch (error: any) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
